# Generated by Django 5.1 on 2024-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок блога')),
                ('content', models.TextField(verbose_name='Содержание блога')),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='Превью блога')),
                ('publish_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'permissions': [('can_edit', 'может редактировать блог')],
            },
        ),
    ]
